global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'podperf-app'
    static_configs:
      - targets: ['podperf_app:8080']
    metrics_path: '/metrics' 